---
- name: Chrony NTP 패키지 설치 
  dnf:
    name: chrony
    state: present

- name: Chrony 설정 파일 배포
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    backup: yes
  notify: restart chrony

- name: 서비스 시작 및 활성화
  systemd:
    name: chronyd
    state: started
    enabled: yes
