---


################################################################
# Play 01: [Role: ftp] 정의 (Target: ansible4)
# 1) FTP 패키지(vsftpd) 설치 및 서비스 기동 확인
# 2) 방화벽 포트(21/tcp) 등록 및 즉시 활성화
# 3) 보안 설정을 위한 익명 사용자(Anonymous) 접근 제한
# 4) 설정 변경 발생 시 서비스 재기동 핸들러 연동
################################################################

################################################################
# Play 02: [Role: mail] 정의 (Target: ansible4)
# 1) SMTP(Postfix) 및 IMAP/POP3(Dovecot) 패키지 일괄 설치
# 2) Mail 통신 필수 방화벽 서비스(smtp, imap, pop3) 일괄 등록
# 3) Postfix 메인 설정 변경 (인터페이스 전체 리슨)
# 4) Dovecot 서비스 프로토콜 활성화 (imap pop3 lmtp)
# 5) 설정 변경 반영을 위한 통합 메일 서비스 재기동 핸들러 연동
################################################################




- name: DNS Server Setup
  hosts: dns_servers
  roles:
    - dns

- name: WEB Server Setup
  hosts: web_servers
  roles:
    - web

- name: WEB 접속 확인
  hosts: localhost
  tasks:
    - name: 웹 접속 확인
      uri:
        url: "http://{{ hostvars['web1']['ansible_host'] }}"
        return_content: true
        status_code: 200