---
- name: WEB Server Setup
  hosts: web_servers
  vars_files:
    - ../group_vars/all.yml
  roles:
    - web

- name: WEB 접속 확인
  hosts: localhost
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: 웹 접속 확인
      uri:
        url: "http://{{ web_ip }}"
        return_content: true
        status_code: 200
